default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: Lunch_and_Learn_development

test:
  <<: *default
  database: Lunch_and_Learn_test

production:
  <<: *default
  database: Lunch_and_Learn_production
  username: Lunch_and_Learn
  password: <%= ENV['LUNCH_AND_LEARN_DATABASE_PASSWORD'] %>
